language: rust
stages:
  - Test

jobs:
  include:
    - stage: Test
      name: Unit Tests
      cache: cargo
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
    - stage: Test
      name: Static Checks
      cache:
        directories:
          - $HOME/.cache/pre-commit
      script:
        - pre-commit install
        - pre-commit run --all-files -v --show-diff-on-failure
 