[package]
name = "rusty-gameboy"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/atskae/rusty-gameboy"
keywords = ["gameboy"]

[dependencies]
env_logger = "0.9"

[dev-dependencies]
cargo-check = "0.2"
