name: GitHub Actions
on: [push]
jobs:
  test:
    runs-on: macos-10.15
    steps:
    - name: Print Run Information
      run: |
        echo "Operating System: ${{ runner.os }}"
        echo "Repository: ${{ github.repository }}."
        echo "Branch: ${{ github.ref }}"
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Checkout Repository Code
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all
    - name: Run Unit Tests
      run: cargo test --verbose --all
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Static Checks
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files -v --hook-stage push
